---
excludes:
  paths:
  - pattern: ".*"
    reason: "DATA_FILE_OF"
    comment: >-
      Configuration files.
  - pattern: "bom.spdx.yml"
    reason: "OTHER"
    comment: >-
      Bill of materials.
  - pattern: "LICENSE.txt"
    reason: "OTHER"
    comment: >-
      The license for this project.
  - pattern: "*.md"
    reason: "DOCUMENTATION_OF"
    comment: >-
      Documentation files.
  - pattern: "THIRD-PARTY-NOTICES.txt"
    reason: "OTHER"
    comment: >-
      FOSS disclosure statement of this project.
  - pattern: "img/**"
    reason: "DOCUMENTATION_OF"
    comment: >-
      Just readme images.
  - pattern: ".*/**"
    reason: "DATA_FILE_OF"
    comment: >-
      Configuration files.
  - pattern: "**/src/Tests/**"
    reason: "TEST_OF"
    comment: >-
      Licenses contained in this directory are used for testing and do not apply to the OSS Review Toolkit.
  - pattern: "deploy/**"
    reason: "OTHER"
    comment: >-
      Built packages.
      