---
# Example for a complete curation object:
#- id: "Maven:org.hamcrest:hamcrest-core:1.3"
#  curations:
#    comment: "An explanation why the curation is needed or the reasoning for a license conclusion."
#    concluded_license: "Apache-2.0 OR BSD-3-Clause" # Valid SPDX license expression to override the license findings.
#    declared_license_mapping:
#      "Copyright (C) 2013, Martin Journois": "NONE"
#      "BSD": "BSD-3-Clause"
#    description: "Curated description."
#    homepage_url: "http://example.com"
#    binary_artifact:
#      url: "http://example.com/binary.zip"
#      hash:
#        value: "ddce269a1e3d054cae349621c198dd52"
#        algorithm: "MD5"
#    source_artifact:
#      url: "http://example.com/sources.zip"
#      hash:
#        value: "ddce269a1e3d054cae349621c198dd52"
#        algorithm: "MD5"
#    vcs:
#      type: "Git"
#      url: "http://example.com/repo.git"
#      revision: "1234abc"
#      path: "subdirectory"
#    is_metadata_only: true # Whether the package is metadata only.
#    is_modified: true # Whether the package is modified compared to the original source.

- id: "NuGet::Moq:4.16.1"
  curations:
    concluded_license: "BSD-3-Clause"
- id: "NuGet:NETStandard:Library:2.0.3"
  curations:
    concluded_license: "MIT"
    vcs:
      type: "Git"
      url: "https://github.com/dotnet/standard.git"
      revision: "18a36291e48808fa7ef2d00a764ceb1ec95645a5"
- id: "NuGet::NUnit:3.13.2"
  curations:
    concluded_license: "MIT"