---
  excludes:
    paths:
    - pattern: "**/{:funTest|test|Tests}/**"
      reason: "TEST_OF"
      comment: >-
        Licenses contained in this directory are used for testing and do not apply to the OSS Review Toolkit.
        