# Create a stable project release. This workflow is manually triggered.

name: Create release (from develop only!)

# Run on manual trigger only
on:
  workflow_dispatch:

jobs:
  release:
    uses: ZEISS-PiWeb/github-actions/.github/workflows/create-release.yml@main
    with:
      generate_release_notes: true
    secrets: inherit
