# Workflow to build and publish the develop branch

name: Build, Test & Pack on develop

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  develop:
    uses: ZEISS-PiWeb/github-actions/.github/workflows/develop.yml@main
    with:
      do_pack: true  
    secrets: inherit