name: Run Software Composition Analysis with ORT

on:
  workflow_dispatch:

jobs:
  ort:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          repository: 'ZEISS-PiWeb/PiWeb-MeshModel'
          ref: 'feature/Automate-SCA'
      - name: Run GitHub Action for ORT
        uses: oss-review-toolkit/ort-ci-github-action@v1
